bbs_sys/urls.py
from django.conf.urls import url
from django.contrib import admin
from appo import views
from bbs_sys import settings
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'index/$',views.index),
    url(r'^register/$', views.register),
    url(r'^check_username/$', views.check_username),
    #点赞点踩
    url(r'^upordown/$',views.upordown),
    url(r'^my_login/$',views.my_login,name='my_login'),
    url(r'^login_code/$',views.login_code),
    url(r'^backend/$',views.backend),
    # url(r'^backend/add_article/$',),
    #添加文章
    url(r'add_article',views.add_article),
    url(r'add_article/$',views.add_article),

    url(r'^my_logout/$',views.my_logout),
    url(r'^update_password/$',views.update_password),
    url(r'^update_avatar/$',views.update_avatar),
    url(r'^media/(?P<path>.*)',serve,{'document_root':settings.MEDIA_ROOT}),
    # url('^(?P<username>\w+)/article/(?P<article_id>\d+)$',)
    #文章详情 /owen/article/?.html
    url(r'^(?P<site>\w+)/article/(?P<aid>\d+).html$',views.article_page,name='article_page'),

    #个人站点
    url(r'^(?P<site>\w+)$',views.site_page),
    url(r'^(?P<site>\w+)/$',views.site_page),
    url(r'edit_article/(?P<article_id>\d+)',views.edit_article),















]

appo/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
用户表：User
username：账号
password：密码
data_joined：注册时间
email: 邮箱
avatar：图像
telephone：电话
blog：博客站点(一对一)
    """
    # 给该字段一个文件对象，该字段会将文件本体存放在upload_to指定的文件夹下，字段内存放文件路径
    avatar = models.FileField(upload_to='avatar', default='static/img/user.png')
    telephone = models.CharField(max_length=11)
    blog = models.OneToOneField(to='Blog', null=True, on_delete=models.SET_NULL, db_constraint=False, blank=True)
    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

class Blog(models.Model):
    """
博客站点表：Blog
site: 站点域名
name：站点名
title：标题
theme：站点主体样式
category：拥有的分类(多对多)
tag: 拥有的标签(多对多)
    """
    site = models.CharField(max_length=32, unique=True)
    title = models.CharField(max_length=64)
    theme = models.CharField(max_length=32)
    category = models.ManyToManyField(to='Category', db_constraint=False)
    tag = models.ManyToManyField(to='Tag', db_constraint=False)

    def __str__(self):
        return self.site
    class Meta:
        verbose_name = "站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
分类表：Category
name：分类名
    """
    name = models.CharField(max_length=16, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "分组"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
标签表：Tag
name：标签名
    """
    name = models.CharField(max_length=16, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


# 接口：该表需要重构
class Article(models.Model):
    """
文章表：Article
title：文章标题
desc：文章摘要
content：文章内容
create_time：发布事件
blog：所属博客站点(一对多)
category：所属分类(一对多)
tag：拥有的标签(多对多)
"""
    title = models.CharField(max_length=32)
    desc = models.CharField(max_length=256)
    # content = models.TextField()
    create_time = models.DateField(auto_now_add=True)
    blog = models.ForeignKey(to='Blog', null=True, on_delete=models.SET_NULL, db_constraint=False)
    # category = models.ForeignKey(to='Category', null=True, on_delete=models.SET_NULL, db_constraint=False)
    # tag = models.ManyToManyField(to='Tag', db_constraint=False)
    article_detail = models.OneToOneField(to='ArticleDetail', null=True, on_delete=models.SET_NULL, db_constraint=False, blank=True)

    # 该文章的具体点赞点踩量，一定要通过代码逻辑保证与UpOrDown表中数据一致
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    # 评论数
    comment_count = models.IntegerField(default=0)


    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

# 文章详情
class ArticleDetail(models.Model):
    content = models.TextField()
    category = models.ForeignKey(to='Category', null=True, on_delete=models.SET_NULL, db_constraint=False)
    tag = models.ManyToManyField(to='Tag', db_constraint=False)

    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name

class UpOrDown(models.Model):
    """
点赞点踩表：UpOrDown  # user与article的点踩关系表
user：点赞点踩用户(一对多)
article：点赞点踩文章(一对多)
is_up：点赞或点踩
    """
    user = models.ForeignKey(to='User', null=True, on_delete=models.SET_NULL, db_constraint=False)
    article = models.ForeignKey(to='Article', null=True, on_delete=models.SET_NULL, db_constraint=False)
    is_up = models.BooleanField()

    def __str__(self):
        return self.user.username + " | " + self.article.title + ">>>" + str(self.is_up)
    # 实际开发这种表存在大量的修改操作，不建议建立索引（索引服务于查询的）
    class Meta:
        unique_together = ('user', 'article')
        verbose_name = "赞踩"
        verbose_name_plural = verbose_name






class Comment(models.Model):
    """
评论表：Comment  # user与article的评论关系表
user：点赞点踩用户(一对多)
article：点赞点踩文章(一对多)
content：评论内容
parent：父评论(自关联, 一对多)
    """
    user = models.ForeignKey(to='User', null=True, on_delete=models.SET_NULL, db_constraint=False)
    article = models.ForeignKey(to='Article', null=True, on_delete=models.SET_NULL, db_constraint=False)
    content = models.TextField()
    # 评论创建的时间
    create_time = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey(to='self', null=True, on_delete=models.SET_NULL, db_constraint=False)


    def __str__(self):
        return str(self.user.id) + "" + str(self.article.id) + "" + str(self.parent)


    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

templates/site/article.html
{% extends 'site/site.html' %}
{% block link %}

    <style>
        .flag {
            position: fixed;
            bottom: 50px;
            right: 50px;
            color: #c0c0c0;
        }

        .up {
            border: 5px solid darkcyan;
            border-radius: 50%;
            padding: 10px;
            font-size: 20px;
        }

        .down {
            border: 5px solid darkslateblue;
            border-radius: 50%;
            padding: 10px;
            font-size: 20px;
            margin-left: 10px;
        }

        .up:hover, .down:hover {
            cursor: pointer;
        }

        .active {
            color: red;
        }

        .blank {
            margin-top: 200px;
        }

        textarea {
            resize: none;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- -->
    <!-- 文章标题 -->
    <h2 class="text-center">{{ article.title }}</h2>
    <hr>
    <!-- 文章内容 -->
    <div>
        {{ article.article_detail.content|safe }}
    </div>
    <!-- 点赞点踩 -->
    <div class="flag">
        <!-- 未登录：空 | 登录未点赞点踩：None | 登录点踩了：{'is_up': True} | 登录点踩了：{'is_up': False} -->
        <i hidden class="is_login" style="color: black; font-size: 30px">{{ is_up }}</i>
        {% if is_up.is_up == True %}
            <i class="up glyphicon glyphicon-thumbs-up active"></i>
            <i class="down glyphicon glyphicon-thumbs-down"></i>
        {% elif is_up.is_up == False %}
            <i class="up glyphicon glyphicon-thumbs-up"></i>
            <i class="down glyphicon glyphicon-thumbs-down active"></i>
        {% else %}
            <i class="up glyphicon glyphicon-thumbs-up"></i>
            <i class="down glyphicon glyphicon-thumbs-down"></i>
        {% endif %}
    </div>
    <!-- 评论 -->
    {% if not request.user.is_authenticated %}
        <h3>
            <a href="">登录后查询评论区域</a>
        </h3>
    {% else %}
        <h3>评论列表</h3>
        <ul class="list-group">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <span>
                        <a href="">#{{ forloop.counter }}楼</a>
                    </span>
                    <span>
                        {{ comment.create_time|date:'Y-m-d H:i:s' }}
                    </span>
                    <span>
                        <a href="">{{ comment.user.username }}</a>
                    </span>
                    <span class="pull-right">
                        <a username="{{ comment.user.username }}" parent_id="{{ comment.id }}" class="back_comment"
                           href="javascript:void(0)">回复</a>
                    </span>
                    {% if comment.parent %}
                        <p>
                            @ {{ comment.parent.user.username }}
                        </p>
                    {% endif %}
                    <p>
                        {{ comment.content }}
                    </p>
                </li>
            {% endfor %}

        </ul>
        <h3>发表评论</h3>
        <p>
            昵称：<input type="text" disabled value="{{ request.user.username }}">
        </p>
        <p>
            评论内容：
        </p>
        <p>
            <textarea class="comment_content" cols="60" rows="10"></textarea>
        </p>
        <p>
            <input id="submit" type="button" class="btn btn-primary" value="评论">
        </p>

    {% endif %}
    <!-- 底部留白 -->
    <div class="blank"></div>
{% endblock %}


{% block script %}
    <script>
        // 赞踩脚本
        $('.up').click(function () {
            // 未登录：空 => false
            // 登录未点赞点踩：None | 登录点踩了：{'is_up': True} | 登录点踩了：{'is_up': False} => true

            is_login = $('.is_login').text() ? true : false;

            if (!is_login) {
                alert("请登录！")
            } else {
                if (!$(this).hasClass('active')) {  // 保证点赞后不再重复点赞
                    _this = this;
                    // 不是点赞状态，发送点赞请求
                    $.ajax({
                        url: '/upordown/',
                        type: 'get',
                        data: {
                            article_id: {{ article.id }},
                            is_up: true,
                        },
                        success: function (data) {
                            console.log(data);
                            data.status == 1 && $(_this).addClass('active').next().removeClass('active');
                        }
                    })
                }
            }
        })

        $('.down').click(function () {
            is_login = $('.is_login').text() ? true : false;
            if (!is_login) {
                alert("请登录！")
            } else {
                if (!$(this).hasClass('active')) {  // 保证点踩后不再重复点踩
                    _this = this;
                    // 不是点踩状态，发送点踩请求
                    $.ajax({
                        url: '/upordown/',
                        type: 'get',
                        data: {
                            article_id: {{ article.id }},
                            is_up: false,
                        },
                        success: function (data) {
                            console.log(data);
                            data.status == 1 && $(_this).addClass('active').prev().removeClass('active');
                        }
                    })
                }
            }

        })

    </script>

    <script>
        var parent_id = '';

        // 回复的点击事件
        $('.back_comment').click(function () {
            var username = $(this).attr('username');
            parent_id = $(this).attr('parent_id');
            {#alert("回复评论")#}
            $(".comment_content").text('@' + username + '\n')
        });

        // 评论脚本
        $("#submit").click(function () {
            var content = $('.comment_content').val();
            var index = content.indexOf('\n');
            content = content.slice(index + 1);

            if (content) {
                $.ajax({
                    url: '/add_comment/',
                    type: 'post',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        article_id: {{ article.id }},
                        content: content,
                        parent_id: parent_id,
                    },
                    success: function (data) {
                        location.reload()
                    }
                })
            }

        })
    </script>
{% endblock %}

templates/site/menu_list.html
<div class="panel panel-primary">
    <div class="panel-heading">文章分类</div>
    <div class="panel-body">
        {% for category_tuple in category_set %}
        <p>
           <a href="">{{ category_tuple.0 }}({{ category_tuple.1 }})</a>
        </p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-info">
    <div class="panel-heading">文章标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p>
              <a href="">{{ tag.name }}({{ tag.c }})</a>
            </p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">文章档案</div>
    {% for time in time_list  %}
        <p>
            <a href="">{{ time.month | date:'Y年m月' }}({{ time.c }})</a>
        </p>
    {% endfor %}

</div>

templates/site/site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人站点</title>
    <link rel="stylesheet" href="/static/css/article.css">
    <link rel="stylesheet" href="/static/bs-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}">

    {% block link %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">博菜园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a id="site" href="">{{ blog.title }}<span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/backend/">后台管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/my_logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/my_login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
    <div class="row">
        {# 展示菜单#}
        <div class="col-md-3">
            {% load blog_tags %}
            {% menu_list_tag blog %}

        </div>
        <div class="col-md-9">
            {% block content %}

            {% endblock %}
            </div>
        </div>
    </div>
</div>

</body>
<script src="/static/bs-3.3.7/js/jquery-3.3.1.js"></script>
<script src="/static/bs-3.3.7/js/bootstrap.js"></script>
{% block script %}

{% endblock %}
</html>

templates/site/site_content.html
{% extends 'site/site.html' %}

{% block content %}
    {% for article in article_list %}
        <h3>
            <a href="/{{ blog.site }}/article/{{ article.id }}.html">{{ article.title }}</a>
        </h3>
        <div class="media clearfix" style="margin-bottom: 30px">
            <div class="media-left media-middle">
                <a hidden href="">
                    <img class="media-object" src="/media/{{ article.blog.user.avatar }}" alt="">
                </a>
            </div>
            <div class="media-body">
                {{ article.desc }}
            </div>
            <div class="pull-right">
                <span><b>{{ article.blog.user.username }}</b></span>
                <span>{{ article.create_time }}</span>
                <span>评论（0）</span>
                {# 连表真心难 #}
                {# <span>点赞（{{ article.upordown_set.all }}）</span>#}
                <span>点赞（{{ article.up_count }}）</span>
                <span>点踩（{{ article.down_count }}）</span>
            </div>
            <hr>
        </div>
    {% endfor %}
{% endblock %}